/*==============================================================*/
/* DBMS name:      MySQL 5.0                                    */
/* Created on:     12-04-2024 11:17:24                          */
/*==============================================================*/

CREATE SCHEMA `voting_system` ;
USE `voting_system`;


drop table if exists CANDIDATES;

drop table if exists COMMUNES;

drop table if exists REGIONS;

drop table if exists VOTES;

/*==============================================================*/
/* Table: CANDIDATES                                            */
/*==============================================================*/
create table CANDIDATES
(
   ID_CANDIDATE         int not null auto_increment comment 'Identificador',
   DIN_CANDIDATE        timestamp not null default CURRENT_TIMESTAMP comment 'Fecha creación',
   NAME_CANDIDATE       text not null comment 'Nombre de candidato',
   primary key (ID_CANDIDATE)
);

/*==============================================================*/
/* Table: COMMUNES                                              */
/*==============================================================*/
create table COMMUNES
(
   ID_COMMUNE           int not null auto_increment comment 'Identificador',
   ID_REGION            int not null comment 'Identificador',
   DIN_COMMUNE          timestamp not null default CURRENT_TIMESTAMP comment 'Fecha creación',
   NAME_COMMUNE         text not null comment 'Comuna',
   primary key (ID_COMMUNE)
);

/*==============================================================*/
/* Table: REGIONS                                               */
/*==============================================================*/
create table REGIONS
(
   ID_REGION            int not null auto_increment comment 'Identificador',
   DIN_REGION           timestamp not null default CURRENT_TIMESTAMP comment 'Fecha creación',
   NAME_REGION          text not null comment 'Región',
   primary key (ID_REGION)
);

/*==============================================================*/
/* Table: VOTES                                                 */
/*==============================================================*/
create table VOTES
(
   ID_VOTE              int not null auto_increment comment 'Identificador',
   ID_COMMUNE           int not null comment 'Identificador',
   ID_CANDIDATE         int not null comment 'Identificador',
   DIN_VOTE             timestamp not null default CURRENT_TIMESTAMP comment 'Fecha votación',
   NAME_VOTE            varchar(150) not null comment 'Nombre & apellido',
   ALIAS_VOTE           varchar(50) comment 'Alias',
   RUT_VOTE             text not null comment 'Rut',
   EMAIL_VOTE           text not null comment 'E-mail',
   WHORRSS_VOTE         int comment '¿Redes sociales?',
   WHOIE_VOTE           int comment '¿Búsqueda en Internet?',
   WHOFRIEND_VOTE       int comment '¿Recomendación de un amigo?',
   WHOTV_VOTE           int comment '¿Anuncio de Televisión?',
   primary key (ID_VOTE)
);

alter table COMMUNES add constraint FK_COMMUNES_REGIONS foreign key (ID_REGION)
      references REGIONS (ID_REGION) on delete restrict on update restrict;

alter table VOTES add constraint FK_VOTES_CANDIDATES foreign key (ID_CANDIDATE)
      references CANDIDATES (ID_CANDIDATE) on delete restrict on update restrict;

alter table VOTES add constraint FK_VOTES_COMMUNES foreign key (ID_COMMUNE)
      references COMMUNES (ID_COMMUNE) on delete restrict on update restrict;


INSERT INTO `regions` (`NAME_REGION`) VALUES ('ARICA Y PARINACOTA');
INSERT INTO `regions` (`NAME_REGION`) VALUES ('TARAPACÁ');
INSERT INTO `regions` (`NAME_REGION`) VALUES ('ANTOFAGASTA');
INSERT INTO `regions` (`NAME_REGION`) VALUES ('ATACAMA');
INSERT INTO `regions` (`NAME_REGION`) VALUES ('COQUIMBO');
INSERT INTO `regions` (`NAME_REGION`) VALUES ('VALPARAÍSO');
INSERT INTO `regions` (`NAME_REGION`) VALUES ('DEL LIBERTADOR GRAL. BERNARDO O\'HIGGINS');
INSERT INTO `regions` (`NAME_REGION`) VALUES ('DEL MAULE');
INSERT INTO `regions` (`NAME_REGION`) VALUES ('DEL BIOBÍO');
INSERT INTO `regions` (`NAME_REGION`) VALUES ('DE LA ARAUCANÍA');
INSERT INTO `regions` (`NAME_REGION`) VALUES ('DE LOS RÍOS');
INSERT INTO `regions` (`NAME_REGION`) VALUES ('DE LOS LAGOS');
INSERT INTO `regions` (`NAME_REGION`) VALUES ('AYSÉN DEL GRAL. CARLOS IBAÑEZ DEL CAMPO');
INSERT INTO `regions` (`NAME_REGION`) VALUES ('MAGALLANES Y DE LA ANTÁRTICA CHILENA');
INSERT INTO `regions` (`NAME_REGION`) VALUES ('METROPOLITANA DE SANTIAGO');

INSERT INTO `candidates` (`NAME_CANDIDATE`) VALUES ('Elton Parker');
INSERT INTO `candidates` (`NAME_CANDIDATE`) VALUES ('Laverne Eaton');
INSERT INTO `candidates` (`NAME_CANDIDATE`) VALUES ('Ray Graves');
INSERT INTO `candidates` (`NAME_CANDIDATE`) VALUES ('Ronnie Pierce');
INSERT INTO `candidates` (`NAME_CANDIDATE`) VALUES ('Jeffrey Sherman');
INSERT INTO `candidates` (`NAME_CANDIDATE`) VALUES ('Robbie Barnes');
INSERT INTO `candidates` (`NAME_CANDIDATE`) VALUES ('Derrick Ferguson');
INSERT INTO `candidates` (`NAME_CANDIDATE`) VALUES ('Mathew Melendez');
INSERT INTO `candidates` (`NAME_CANDIDATE`) VALUES ('Irwin Juarez');
INSERT INTO `candidates` (`NAME_CANDIDATE`) VALUES ('Wiley Mack');

INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('1',"ARICA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('1',"CAMARONES");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('1',"PUTRE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('1',"GENERAL LAGOS");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('2',"IQUIQUE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('2',"ALTO HOSPICIO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('2',"POZO ALMONTE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('2',"CAMIÑA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('2',"COLCHANE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('2',"HUARA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('2',"PICA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('3',"ANTOFAGASTA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('3',"MEJILLONES");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('3',"SIERRA GORDA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('3',"TALTAL");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('3',"CALAMA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('3',"OLLAGÜE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('3',"SAN PEDRO DE ATACAMA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('3',"TOCOPILLA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('3',"MARÍA ELENA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('4',"COPIAPÓ");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('4',"CALDERA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('4',"TIERRA AMARILLA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('4',"CHAÑARAL");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('4',"DIEGO DE ALMAGRO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('4',"VALLENAR");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('4',"ALTO DEL CARMEN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('4',"FREIRINA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('4',"HUASCO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('5',"LA SERENA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('5',"COQUIMBO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('5',"ANDACOLLO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('5',"LA HIGUERA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('5',"PAIGUANO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('5',"VICUÑA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('5',"ILLAPEL");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('5',"CANELA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('5',"LOS VILOS");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('5',"SALAMANCA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('5',"OVALLE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('5',"COMBARBALÁ");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('5',"MONTE PATRIA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('5',"PUNITAQUI");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('5',"RÍO HURTADO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"VALPARAÍSO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"CASABLANCA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"CONCÓN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"JUAN FERNÁNDEZ");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"PUCHUNCAVÍ");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"QUINTERO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"VIÑA DEL MAR");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"ISLA DE PASCUA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"LOS ANDES");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"CALLE LARGA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"RINCONADA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"SAN ESTEBAN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"LA LIGUA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"CABILDO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"PAPUDO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"PETORCA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"ZAPALLAR");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"QUILLOTA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"CALERA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"HIJUELAS");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"LA CRUZ");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"NOGALES");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"SAN ANTONIO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"ALGARROBO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"CARTAGENA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"EL QUISCO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"EL TABO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"SANTO DOMINGO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"SAN FELIPE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"CATEMU");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"LLAILLAY");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"PANQUEHUE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"PUTAENDO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"SANTA MARÍA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"LIMACHE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"QUILPUÉ");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"VILLA ALEMANA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('6',"OLMUÉ");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"RANCAGUA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"CODEGUA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"COINCO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"COLTAUCO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"DOÑIHUE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"GRANEROS");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"LAS CABRAS");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"MACHALÍ");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"MALLOA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"MOSTAZAL");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"OLIVAR");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"PEUMO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"PICHIDEGUA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"QUINTA DE TILCOCO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"RENGO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"REQUÍNOA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"SAN VICENTE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"PICHILEMU");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"LA ESTRELLA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"LITUECHE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"MARCHIHUE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"NAVIDAD");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"PAREDONES");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"SAN FERNANDO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"CHÉPICA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"CHIMBARONGO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"LOLOL");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"NANCAGUA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"PALMILLA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"PERALILLO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"PLACILLA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"PUMANQUE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('7',"SANTA CRUZ");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('8',"TALCA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('8',"CONSTITUCIÓN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('8',"CUREPTO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('8',"EMPEDRADO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('8',"MAULE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('8',"PELARCO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('8',"PENCAHUE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('8',"RÍO CLARO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('8',"SAN CLEMENTE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('8',"SAN RAFAEL");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('8',"CAUQUENES");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('8',"CHANCO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('8',"PELLUHUE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('8',"CURICÃ");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('8',"HUALAÑÉ");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('8',"LICANTÉN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('8',"MOLINA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('8',"RAUCO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('8',"ROMERAL");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('8',"SAGRADA FAMILIA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('8',"TENO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('8',"VICHUQUÉN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('8',"LINARES");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('8',"COLBÚN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('8',"LONGAVÍ");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('8',"PARRAL");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('8',"RETIRO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('8',"SAN JAVIER");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('8',"VILLA ALEGRE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('8',"YERBAS BUENAS");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"CONCEPCIÓN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"CORONEL");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"CHIGUAYANTE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"FLORIDA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"HUALQUI");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"LOTA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"PENCO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"SAN PEDRO DE LA PAZ");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"SANTA JUANA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"TALCAHUANO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"TOMÉ");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"HUALPÉN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"LEBU");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"ARAUCO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"CAÑETE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"CONTULMO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"CURANILAHUE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"LOS ALAMOS");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"TIRÚA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"LOS ANGELES");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"ANTUCO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"CABRERO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"LAJA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"MULCHÉN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"NACIMIENTO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"NEGRETE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"QUILACO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"QUILLECO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"SAN ROSENDO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"SANTA BÁRBARA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"TUCAPEL");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"YUMBEL");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"ALTO BIOBÍO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"CHILLÁN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"BULNES");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"COBQUECURA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"COELEMU");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"COIHUECO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"CHILLÁN VIEJO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"EL CARMEN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"NINHUE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"ÑIQUÉN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"PEMUCO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"PINTO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"PORTEZUELO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"QUILLÓN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"QUIRIHUE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"RÁNQUIL");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"SAN CARLOS");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"SAN FABIÁN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"SAN IGNACIO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"SAN NICOLÁS");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"TREGUACO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('9',"YUNGAY");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('10',"TEMUCO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('10',"CARAHUE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('10',"CUNCO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('10',"CURARREHUE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('10',"FREIRE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('10',"GALVARINO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('10',"GORBEA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('10',"LAUTARO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('10',"LONCOCHE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('10',"MELIPEUCO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('10',"NUEVA IMPERIAL");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('10',"PADRE LAS CASAS");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('10',"PERQUENCO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('10',"PITRUFQUÉN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('10',"PUCÓN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('10',"SAAVEDRA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('10',"TEODORO SCHMIDT");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('10',"TOLTÉN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('10',"VILCÚN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('10',"VILLARRICA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('10',"CHOLCHOL");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('10',"ANGOL");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('10',"COLLIPULLI");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('10',"CURACAUTÍN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('10',"ERCILLA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('10',"LONQUIMAY");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('10',"LOS SAUCES");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('10',"LUMACO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('10',"PURÉN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('10',"RENAICO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('10',"TRAIGUÉN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('10',"VICTORIA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('11',"VALDIVIA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('11',"CORRAL");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('11',"LANCO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('11',"LOS LAGOS");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('11',"MÁFIL");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('11',"MARIQUINA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('11',"PAILLACO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('11',"PANGUIPULLI");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('11',"LA UNIÓN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('11',"FUTRONO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('11',"LAGO RANCO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('11',"RÍO BUENO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('12',"PUERTO MONTT");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('12',"CALBUCO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('12',"COCHAMÓ");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('12',"FRESIA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('12',"FRUTILLAR");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('12',"LOS MUERMOS");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('12',"LLANQUIHUE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('12',"MAULLÍN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('12',"PUERTO VARAS");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('12',"CASTRO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('12',"ANCUD");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('12',"CHONCHI");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('12',"CURACO DE VÉLEZ");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('12',"DALCAHUE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('12',"PUQUELDÓN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('12',"QUEILEN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('12',"QUELLÓN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('12',"QUEMCHI");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('12',"QUINCHAO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('12',"OSORNO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('12',"PUERTO OCTAY");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('12',"PURRANQUE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('12',"PUYEHUE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('12',"RÍO NEGRO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('12',"SAN JUAN DE LA COSTA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('12',"SAN PABLO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('12',"CHAITÉN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('12',"FUTALEUFÚ");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('12',"HUALAIHUÉ");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('12',"PALENA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('13',"COIHAIQUE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('13',"LAGO VERDE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('13',"AISÉN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('13',"CISNES");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('13',"GUAITECAS");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('13',"COCHRANE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('13',"O'HIGGINS");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('13',"TORTEL");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('13',"CHILE CHICO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('13',"RÍO IBÁÑEZ");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('14',"PUNTA ARENAS");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('14',"LAGUNA BLANCA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('14',"RÍO VERDE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('14',"SAN GREGORIO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('14',"CABO DE HORNOS");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('14',"ANTÁRTICA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('14',"PORVENIR");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('14',"PRIMAVERA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('14',"TIMAUKEL");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('14',"NATALES");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('14',"TORRES DEL PAINE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"SANTIAGO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"CERRILLOS");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"CERRO NAVIA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"CONCHALÍ");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"EL BOSQUE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"ESTACIÓN CENTRAL");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"HUECHURABA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"INDEPENDENCIA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"LA CISTERNA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"LA FLORIDA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"LA GRANJA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"LA PINTANA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"LA REINA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"LAS CONDES");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"LO BARNECHEA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"LO ESPEJO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"LO PRADO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"MACUL");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"MAIPÚ");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"ÑUÑOA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"PEDRO AGUIRRE CERDA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"PEÑALOLÉN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"PROVIDENCIA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"PUDAHUEL");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"QUILICURA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"QUINTA NORMAL");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"RECOLETA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"RENCA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"SAN JOAQUÍN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"SAN MIGUEL");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"SAN RAMÓN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"VITACURA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"PUENTE ALTO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"PIRQUE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"SAN JOSÉ DE MAIPO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"COLINA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"LAMPA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"TILTIL");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"SAN BERNARDO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"BUIN");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"CALERA DE TANGO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"PAINE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"MELIPILLA");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"ALHUÉ");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"CURACAVÍ");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"MARÍA PINTO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"SAN PEDRO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"TALAGANTE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"EL MONTE");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"ISLA DE MAIPO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"PADRE HURTADO");
INSERT INTO `communes` (`ID_REGION`, `NAME_COMMUNE`) VALUES ('15',"PEÑAFLOR");
